language: clojure
lein: 2.9.1

services:
  - redis-server

addons:
  hosts:
    - local.host

jdk:
  - oraclejdk11
  - openjdk8

script: lein with-profile +1.8:+1.9:+1.10 cloverage --coveralls

after_success:
  - curl -F json_file=@target/coverage/coveralls.json https://coveralls.io/api/v1/jobs
  - lein deploy clojars
